In [2]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import load_cifar

<p style="font-size:20px">You will define the preprocessing functions in <b>load_cifar.py</b>. Once you are done, you can verify the functions in this template and prepare your data well.</p>

In [3]:
#define your folder directory
folder_path = 'C:/Users/ERSL-1/Desktop/PracticalIntroductionNN-master2/PracticalIntroductionNN-master/HW2_template/'
#folder_path = ''
#folder_path = 'C:\Users\ERSL-1\Desktop\PracticalIntroductionNN-master2\PracticalIntroductionNN-master\HW2_template\''

<h1>load data</h1>
<p style="font-size:20px">Check your functinons load_training_batch and load_testing_batch function are correct.

In [3]:
'''
#######example: load the data_batch_1 , FEEL FREE TO CHANGE #######
batch_1 = load_cifar.load_training_batch(folder_path,1)
#print(batch_1)

######VERIFY THE KEYS, SHAPE OF EACH BATCH #####
print(batch_1.keys())
#make sure you see the keys are ['batch_label','labels','data','filenames']
features_1 = batch_1['data']
print(features_1.shape)
#you should see the shape is (10000,3072)
labels_1 = batch_1['labels']
print(len(labels_1))
#the length of labels_1 should be 10000
'''

features_1, labels_1 = load_cifar.load_training_batch(folder_path,1)
print(features_1.shape)
print(len(labels_1))

(10000, 3072)
10000


<h1>features reshape</h1>
<p style="font-size:20px">Verify features_reshape() function.

In [4]:
######example: reshape the features of batch_1 , FEEL FREE TO CHANGE#####
features_1 = load_cifar.features_reshape(features_1)
print(features_1.shape)
#you should see the shape is (10000,32,32,3)



(10000, 32, 32, 3)


<h1>display data stat (optional)</h1>
<p style="font-size:20px">If you implement this function, you could see the stats of specific batch data and also you can visualize specific data image</p>

In [5]:
#check the 7000 example of batch_3, you should see an "airplane"
#Not implemented
#data_id = 7000
#batch_id = 3
#display_data_stat(folder_path,batch_id,data_id)

<h1>Run preprocess data function</h1>
<p style="font-size:20px">This functions will load all training and testing batches, separate the validation set, and save them as "Pickle" objects</p>

In [5]:
load_cifar.preprocess_data(folder_path)

<h1>load preprocessed training,validation and testing data</h1>
<p style="font-size:20px">Check the shape of your preprocessed data files</p>

In [4]:
#### EXAMPLE, FEEL FREE TO CHANGE #####
'''
valid_features, valid_labels = pickle.load(open('processed_validate','rb'))
training_features, training_labels = pickle.load(open('processed_train1','rb'))
test_features, test_labels = pickle.load(open('processed_test','rb'))
'''

valid_dict = pickle.load(open('processed_validate','rb'))
train_dict1 = pickle.load(open('processed_train1','rb'))
train_dict2 = pickle.load(open('processed_train2','rb'))
test_dict  = pickle.load(open('processed_test','rb'))

valid_features = valid_dict['normal feature']
valid_labels   = valid_dict['one hot labels']

train_features1 = train_dict1['normal feature']
train_labels1   = train_dict1['one hot labels']

train_features2 = train_dict2['normal feature']
train_labels2   = train_dict2['one hot labels']

test_features = test_dict['normal feature']
test_labels   = test_dict['one hot labels']

X = np.concatenate((train_features1,train_features2,train_features1))
Y = train_labels1 + train_labels2

num_steps = 0
batch_x_train = train_features1[num_steps*1028:(num_steps+1)*1028,:]

print(np.shape(X))
print(np.shape(Y))
print(np.shape(batch_x_train))

(30000, 3072)
(10000, 10)
(1028, 3072)


In [5]:
#check the shape of data and labels, please make sure there is no error
#before you implement your neural network.
print(np.shape(train_features1))
print(np.shape(train_labels1))

print(train_features1)

(10000, 3072)
(10000, 10)
[[0.23137255 0.16862745 0.19607843 ... 0.54901961 0.32941176 0.28235294]
 [0.60392157 0.49411765 0.41176471 ... 0.54509804 0.55686275 0.56470588]
 [1.         0.99215686 0.99215686 ... 0.3254902  0.3254902  0.32941176]
 ...
 [0.27843137 0.23529412 0.29019608 ... 0.26666667 0.27058824 0.26666667]
 [0.98039216 0.99607843 0.82745098 ... 0.84313725 1.         0.99607843]
 [0.24313725 0.23921569 0.23529412 ... 0.50980392 0.50980392 0.51372549]]
